// app/data.ts
import { Ingredient, Cocktail } from "../types";

export const INGREDIENTS: Ingredient[] = [
  {
    id: "ingredient-typescript",
    name: "TypeScript",
    type: "Language",
    characteristics: "",
    extraData: "",
    code: "",
    table: [],
  },
  {
    id: "ingredient-javascript",
    name: "JavaScript",
    type: "Language",
    characteristics: "",
    extraData: "",
    code: "",
    table: [],
  },
  {
    id: "ingredient-reactjs",
    name: "ReactJS",
    type: "Library",
    characteristics: "",
    extraData: "",
    code: "",
    table: [],
  },
  {
    id: "ingredient-nextjs",
    name: "NextJS",
    type: "Framework",
    characteristics: "",
    extraData: "",
    code: "",
    table: [],
  },
  {
    id: "ingredient-tailwindcss",
    name: "TailwindCSS",
    type: "Tool",
    characteristics: "",
    extraData: "",
    code: "",
    table: [],
  },
  {
    id: "ingredient-vite",
    name: "Vite",
    type: "Tool",
    characteristics: "",
    extraData: "",
    code: "",
    table: [],
  },
  {
    id: "ingredient-sql",
    name: "SQL",
    type: "Language",
    characteristics: "",
    extraData: "",
    code: "",
    table: [],
  },
];
